// Code generated by goctl. DO NOT EDIT.
package types

type DeviceDeleteRequest struct {
	Identity string `json:"identity"`
}

type DeviceDeleteReply struct {
}

type DeviceModifyRequest struct {
	Identity string `json:"identity"`
	DeviceCreateRequest
}

type DeviceModifyReply struct {
}

type DeviceCreateRequest struct {
	Name            string `json:"name"`
	ProductIdentity string `json:"product_identity"`
}

type DeviceCreateReply struct {
}

type ProductDeleteRequest struct {
	Identity string `json:"identity"`
}

type ProductDeleteReply struct {
}

type ProductModifyRequest struct {
	Identity string `json:"identity"`
	ProductCreateRequest
}

type ProductModifyReply struct {
}

type ProductCreateRequest struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type ProductCreateReply struct {
}

type ProductListRequst struct {
	BaseRequest
}

type ProductListReply struct {
	List  []*ProductListBaisc `json:"list"`
	Count int64               `json:"count"`
}

type ProductListBaisc struct {
	Identity  string `json:"identity"`
	Key       string `json:"key"`
	Name      string `json:"name"`
	Desc      string `json:"desc"`
	CreatedAt string `json:"created_at"`
}

type DeviceListRequest struct {
	BaseRequest
}

type DeviceListBaisc struct {
	Identity       string `json:"identity"`
	Name           string `json:"name"`
	Key            string `json:"key"`
	Secret         string `json:"secret"`
	ProductName    string `json:"product_name"`
	LastOnlineTime int64  `json:"last_online_time"`
}

type DeviceListReply struct {
	List  []*DeviceListBaisc `json:"list"`
	Count int64              `json:"count"`
}

type BaseRequest struct {
	Page int    `json:"page,optional"`
	Size int    `json:",optional"`
	Name string `json:"name,optional"`
}
