// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginReply struct {
	Token string `json:"token"`
}
