// Code generated by goctl. DO NOT EDIT.
package types

type SendMessageRequest struct {
	ProductKey string `json:"product_key"`
	DeviceKey  string `json:"device_key"`
	Data       string `json:"data"`
}

type SendMessageReply struct {
}
